version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: examlify-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: examlify_dev
      MYSQL_USER: examify_user
      MYSQL_PASSWORD: examify_pass
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password